name: Master CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-posix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: >
        sudo apt update && sudo apt install -y 
        cmake g++ clang-tidy cppcheck python3 libssl-dev libcrypt-dev libfuse3-dev qt6-base-dev libgl1-mesa-dev
    - name: Install (ubuntu-20.04)
      if: matrix.os == 'ubuntu-20.04'
      run: >
        sudo apt update && sudo apt install -y 
        cmake g++ clang-tidy cppcheck python3 libssl-dev libcrypt-dev libfuse-dev qtbase5-dev
    - name: Build and Test
      run: tools/builddev
